# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85e24e9f636222b4fd792c210b2fb776d73f91eff4d11cc2e9d6e096c633c24ade9f9fa1778f38c000f096f2fae6e421a64196a6b7c7b8e5fd13f3374d8342a3

test:
  secret_key_base: ddd297a4b787b23167589e4c39e91337f32abfde7cf51525ac3f7fbbf43d7873b7bfc90b6a658e8dd415cc872a00e36afdf108db0efe0d565103fa567ac7b33d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
